apiVersion: v1
kind: Pod
metadata:
  name: mon-alpine
spec:
  nodeName: gmorini-manager-linux-1 # schedule pod to specific node
  containers:
  - name: alpine
    image: guismo/mon_alpine:latest
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
